''' lineout everywhere '''
plt.figure(figsize=(12,6))
plot_lineout(mwf, 'C1', label='on crystal 0')
plot_lineout(mwf_c1, 'C2', label='on crystal 1')
plot_lineout(mwf_l0, 'C3', label='on lens 0')
plot_lineout(mwf_apt, 'C4', label='on slit')
plot_lineout(mwf_l1, 'C5', label='on lens 1')
plot_lineout(mwf_c2, 'C6', label='on crystal 2')
plot_lineout(mwf_c3, 'C7', label='on crystal 3')
plot_lineout(mwf_det, 'C8', label='on det')

''' spectra everywhere '''
plt.figure(figsize=(12,6))
awc0, evc0, intc0s = plot_spectra(mwf, 'C1', label='on crystal 0')
awc1, evc1, intc1s = plot_spectra(mwf_c1, 'C2', label='on crystal 1')
awl0, evl0, intl0s = plot_spectra(mwf_l0, 'C3', label='on lens 0')
awapt, evapt, intapts = plot_spectra(mwf_apt,'C4', label='on slit')
awl1, evl1, intl1s = plot_spectra(mwf_l1, 'C5', label='on lens 1')
awc2, evc2, intc2s = plot_spectra(mwf_c2, 'C6', label='on crystal 2')
awc3, evc3, intc3s = plot_spectra(mwf_c3, 'C7', label='on crystal 3')
awdet, evdet, intdets = plot_spectra(mwf_det,'C8', label='on det')

''' temporal profilfe everywhere '''
plt.figure(figsize=(12,6))
awc0, tc0, intc0t = plot_temporal(mwf, 'C1', label='on crystal 0',fov=200e-15, pulse_duration = pulse_duration)
awc1, tc1, intc1t = plot_temporal(mwf_c1, 'C2', label='on crystal 1',fov=200e-15, pulse_duration = pulse_duration)
awl0, tl0, intl0t = plot_temporal(mwf_l0, 'C3', label='on lens 0',fov=200e-15, pulse_duration = pulse_duration)
awapt, tapt, intaptt = plot_temporal(mwf_apt,'C4', label='on slit',fov=200e-15, pulse_duration = pulse_duration)
awl1, tl1, intl1t = plot_temporal(mwf_l1, 'C5', label='on lens 1',fov=200e-15, pulse_duration = pulse_duration)
awc2, tc2, intc2t = plot_temporal(mwf_c2, 'C6', label='on crystal 2',fov=200e-15, pulse_duration = pulse_duration)
awc3, tc3, intc3t = plot_temporal(mwf_c3, 'C7', label='on crystal 3',fov=200e-15, pulse_duration = pulse_duration)
awdet, tdet, intdett = plot_temporal(mwf_det,'C8', label='on det',fov=200e-15, pulse_duration = pulse_duration)